### ISSUE TITLE
Не работает выдача сертификатов для поддоменов

### ISSUE THREAD

**Issue by hywax** [artrey/certbot-dns-timeweb#2]
На данный момент невозможно создать сертификат для поддоменов. 

Проблема на стороне работы с timeweb api. Используется [getDomainDNSRecords](https://timeweb.cloud/api-docs#tag/Domeny/operation/getDomainDNSRecords), в которую необходимо передать домен 2 уровня, а мы передаем в [_perform](https://github.com/artrey/certbot-dns-timeweb/blob/master/certbot_dns_timeweb/authenticator.py#L45) домен напрямую. Если туда придет поддомен вида `sub.example.ru`, то timeweb ответит ошибкой `Bad DNS record type` (тк ожидает именно root домен).

❌ Будет ошибка:
```sh
curl -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer ****" \
  -d '{"type":"TXT","value":"test","subdomain":"*.sub"}' \
  "https://api.timeweb.cloud/api/v1/domains/sub.site.ru/dns-records"
```

✅ Как правильно:
```sh
curl -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer ****" \
  -d '{"type":"TXT","value":"test","subdomain":"*.sub"}' \
  "https://api.timeweb.cloud/api/v1/domains/site.ru/dns-records"
```

Сделал фикс, но я не python разработчик. Так что если есть какие-то ошибки, то укажи мне на них или исправь сам, если сможешь.

**Comment by artrey** [comment]
поправил, версия 1.0.1
